### ISSUE TITLE
 Peak Stimulation

### ISSUE THREAD

**Issue by KengChiLiu** [ZhouYanzhao/PRM#1]
Hi @ZhouYanzhao 

May I ask how did you implement  Peak Stimulation (local max) ?
Did you build a custom layer or by existing pytorch function ?
I'm trying to build one, but still haven't come up with a solution which makes it differentiable yet.

**Comment by ZhouYanzhao** [comment]
Hi @KengChiLiu 
It was originally implemented by a custom layer. But I am refactoring the code to simplify the implementation and incorporate the API changes of the latest pytorch. The code is expected to be released before the conference. Many thanks for your patience!

**Comment by KengChiLiu** [comment]
Sure~ 
Thanks

**Comment by bityangke** [comment]
Hi Yanzhao
In Table 1，Does “Ours (w/o Peak Stimulation)”  use GAP？
Thanks！
