### ISSUE TITLE
Where is modules.rle_decode?

### ISSUE THREAD

**Issue by FzuLJ** [ZhouYanzhao/PRM#11]
In demo/main.ipynb, In[11] line 6, `proposals = list(map(modules.rle_decode, json.load(f)))`. I can not find rle_decode in config.yml. Does any one know where can I find it? Thanks.

**Comment by FzuLJ** [comment]
I found it in Nest-pytorch.

**Comment by monjurulkarim** [comment]
@FzuLJ Hi, can you please tell me, where exactly did you find it?

**Comment by FzuLJ** [comment]
> @FzuLJ Hi, can you please tell me, where exactly did you find it?

Hi, @monjurulkarim if you have installed Nest as the guidance of installation in the README. You will get a file named Nest-pytorch. The function rle_decode is in Nest-pytorch/install/utils.py

**Comment by monjurulkarim** [comment]
@FzuLJ Many thanks. I got it.
Another question, how did you get the proposals?

**Comment by FzuLJ** [comment]
@monjurulkarim I think this issue will help you. #10
