### ISSUE TITLE
Any news on the implementation?

### ISSUE THREAD

**Issue by MayankSingal** [ZhouYanzhao/PRM#2]
Will the implementation be open sourced soon? Amazing work btw.

**Comment by ZhouYanzhao** [comment]
@MayankSingal 
Sorry for the delay, I'm working on a tight schedule recently. The refactoring is almost done, but it's going to take some time to document and prepare a demo notebook. Thanks for your patience!

**Comment by ZhouYanzhao** [comment]
The code is now available. Not just PRM but [Nest](https://github.com/ZhouYanzhao/Nest), a flexible deep learning module manager I created during the refactoring. To increase reusability, some of the features in the original implementation, such as network training, datasets, logging, were abstracted and moved into Nest's built-in Pytorch module set.
