### ISSUE TITLE
KeyError: 'Could not find a Nest module matches query "*fc_resnet50".'

### ISSUE THREAD

**Issue by monjurulkarim** [ZhouYanzhao/PRM#27]
In the demo file, when I try to run : run_tasks('./config.yml'). I am getting the following error.
KeyError: 'Could not find a Nest module matches query "*fc_resnet50".'

Could you please help me solve this.

**Comment by chuchienshu** [comment]
@monjurulkarim try an [ultra-thin](https://github.com/chuchienshu/ultra-thin-PRM) reconstruction？

**Comment by monjurulkarim** [comment]
@chuchienshu Thanks! you ultra-thin version is working fine.
