### ISSUE TITLE
Is there a downloadable link to the model snapshot? 

### ISSUE THREAD

**Issue by IssamLaradji** [ZhouYanzhao/PRM#5]
I am trying to load `./snapshots/model_latest.pt` to run the `main.ipynb` notebook. Is there a link to the latest model?

Thank you.

**Comment by ZhouYanzhao** [comment]
Hi @IssamLaradji ,
The model snapshot is created by executing the fifth cell, i.e., `run_tasks('./config.yml')`. If you encounter tqdm related errors, please make sure the **widgetsnbextension** is properly activated: `jupyter nbextension enable --py --sys-prefix widgetsnbextension`

**Comment by IssamLaradji** [comment]
Thanks! :)
